# Generated by Django 2.2 on 2019-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品名字')),
                ('goods_count', models.IntegerField(default=0, verbose_name='商品数量')),
                ('goods_price', models.FloatField(default=0, verbose_name='商品价格')),
                ('goods_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品类型')),
                ('goods_birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品产地')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
    ]
